name: webfly_permission
description: WebF native module for permission_handler (Dart + TS).
version: 0.1.0

publish_to: none

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^12.0.1
  webf: ^0.24.11
  webfly_bridge:
    path: ../webfly_bridge
  logging: ^1.3.0
